## https://taplo.tamasfe.dev/configuration/file.html
#:schema = "taplo://taplo.toml"
include = ["*.toml"]

[schema]
path = "http://json.schemastore.org/pyproject"
enabled = true

# |        option         |                                                          description                                                           | default value  |
# | :-------------------: | :----------------------------------------------------------------------------------------------------------------------------: | :------------: |
# |     align_entries     |       Align entries vertically. Entries that have table headers, comments, or blank lines between them are not aligned.        |     false      |
# |    align_comments     | Align consecutive comments after entries and items vertically. This applies to comments that are after entries or array items. |      true      |
# | array_trailing_comma  |                                           Put trailing commas for multiline arrays.                                            |      true      |
# |   array_auto_expand   |                   Automatically expand arrays to multiple lines when they exceed `column_width` characters.                    |      true      |
# |  array_auto_collapse  |                                     Automatically collapse arrays if they fit in one line.                                     |      true      |
# |    compact_arrays     |                                       Omit whitespace padding inside single-line arrays.                                       |      true      |
# | compact_inline_tables |                                         Omit whitespace padding inside inline tables.                                          |     false      |
# |  inline_table_expand  |                                       Expand values (e.g. arrays) inside inline tables.                                        |      true      |
# |    compact_entries    |                                                  Omit whitespace around `=`.                                                   |     false      |
# |     column_width      |                          Target maximum column width after which arrays are expanded into new lines.                           |       80       |
# |     indent_tables     |                                            Indent subtables if they come in order.                                             |     false      |
# |    indent_entries     |                                                  Indent entries under tables.                                                  |     false      |
# |     indent_string     |                        Indentation to use, should be tabs or spaces but technically could be anything.                         | 2 spaces (" ") |
# |   trailing_newline    |                                              Add trailing newline to the source.                                               |      true      |
# |     reorder_keys      |                               Alphabetically reorder keys that are not separated by blank lines.                               |     false      |
# |    reorder_arrays     |                           Alphabetically reorder array values that are not separated by blank lines.                           |     false      |
# |  allowed_blank_lines  |                                     The maximum amount of consecutive blank lines allowed.                                     |       2        |
# |         crlf          |                                                     Use CRLF line endings.                                                     |     false      |

# SOURCE: https://github.com/tamasfe/taplo/blob/4890bd426ce432a97596944ca6496979ff757355/site/site/configuration/formatter-options.md
# default formatting rules for everything in pyproject
[[rule]]
include = ["pyproject.toml"]

[rule.formatting]
array_auto_collapse = false
compact_arrays = true
compact_inline_tables = true
indent_string = "    "       # pdm uses 4 spaces
reorder_arrays = false

# override formatting specifically for these ruff keys
[[rule]]
include = ["pyproject.toml"]
keys = [
    "tool.ruff.lint.select",
    "tool.ruff.lint.ignore",
    "tool.ruff.lint.extend-select",
    "tool.ruff.per-file-ignores",
    "tool.rye.dev-dependencies",
    "dependencies"
]

[rule.formatting]
# Collapse arrays that don't exceed the maximum column width and don't contain comments.
array_auto_collapse = false
# Omit white space padding from single-line arrays
compact_arrays = true
# Omit white space padding from the start and end of inline tables.
compact_inline_tables = true
# Alphabetically reorder keys that are not separated by blank lines.
reorder_keys = true
# Indent subtables if they come in order.
indent_tables = false
# Alphabetically reorder array values that are not separated by blank lines.
reorder_arrays = true
# Indentation to use, should be tabs or spaces but technically could be anything.
indent_string = "    "
