name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  # Allow manual workflow trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          # Set up a virtual environment
          uv venv
          # Install documentation dependencies using the Makefile target
          make docs-setup

      - name: Deploy documentation
        run: |
          # Create an empty .nojekyll file to disable Jekyll processing
          touch .nojekyll

          # Configure git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Deploy with MkDocs using the Makefile target
          make docs-deploy
