name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
  # Allow manual workflow trigger
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Add macos-latest if needed: os: [ubuntu-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set shell path
        id: set-shell
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "macOS" ]]; then
            echo "SHELL_PATH=/opt/homebrew/bin/zsh" >> $GITHUB_ENV
          else
            echo "SHELL_PATH=/bin/bash" >> $GITHUB_ENV
          fi
          echo "Shell path set to: $SHELL_PATH"

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          cache: true
          version: "0.6.3"

      - name: Install dependencies
        env:
          UV_PROJECT_ENVIRONMENT: true
          UV_NO_PROMPT: 1
        shell: ${{ env.SHELL_PATH }} -e {0}
        run: |
          # Set up a virtual environment
          uv venv
          # Install documentation dependencies using the Makefile target
          make docs-setup

      - name: Deploy documentation
        shell: ${{ env.SHELL_PATH }} -e {0}
        run: |
          # Create an empty .nojekyll file to disable Jekyll processing
          touch .nojekyll

          # Configure git user
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Deploy with MkDocs using the Makefile target
          make docs-deploy

      - name: Prune cache
        shell: ${{ env.SHELL_PATH }} -e {0}
        run: uv cache prune --ci
